services:
  app:
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./app/.env
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./app/.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: